[package]
name = "json-validator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonschema = "~0"
serde_json = "~1"
actix-web = "~4"
lazy_static = "~1"
log = "~0"
env_logger = "~0"
walkdir = "~2"
